---
version: 2

models:            
  - name: reformat_persons
    description: "Remove blank, punctuation, numbers in persons"
    config:
      not_run_models: "{{ var('not_run_models') }}"
    docs:
      show: "{{ 'reformat_persons' not in var('not_run_models')}}"
      node_color: '#DB7995'